In [2]:
from scipy.io import loadmat
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt

mtxN = loadmat('mtxExamples.mat')


Matrix 1

In [3]:
mtx1 = mtxN['mtx1']
mtx2 = mtxN['mtx2']
mtx3 = mtxN['mtx3']
mtx4 = mtxN['mtx4']
print(mtx1)

[[ 6.14755957  0.02271354]
 [-2.1313486   8.21732199]
 [ 6.01301737  3.09142304]]


In [24]:
def search_spaces(M):
    U, s, V = np.linalg.svd(M, full_matrices = True)
    ## Search for null basis 
    index_null = np.where(s<1e-5)
    null_basis = []
    for i in index_null[0]:
        null_basis.append(V[:,i])
    n_null = len(null_basis)
    weights = np.random.randn(n_null)
    rand_vector = np.array(null_basis).T@weights
    y = M*rand_vector
    if y.all() > 1e-20:
        print('Null space is defined by {}'.format(null_basis))
        print('Verified by random vector {}'.format(rand_vector))
    else:
        print('Only null space is from the zero vector')
        
    index_range = np.where(s < 1e-5)
    range_basis = []
    # try:
    for i in index_range[0]:
        range_basis.append(U[:,i])
    n_range = len(range_basis)
    weights = np.random.randn(n_range)
    rand_vector = np.array(range_basis).T@weights
    
    try: 
        y = M*rand_vector
        x = y*la.inv(M)
        print('Range space is defined by {}'.format(null_basis))
        print('Verified by random vector y: {}'.format(rand_vector))
        print('Solving the linear system for x yielded: {}'.format(x))
    except: 
        print('The matrix is not invertible')



search_spaces(mtx1)
search_spaces(mtx2)
search_spaces(mtx3)
search_spaces(mtx4)



Only null space is from the zero vector
The matrix is not invertible
Null space is defined by [array([-0.01209688, -0.44405777,  0.89591649]), array([ 0.99988947, -0.01311701,  0.00699935])]
Verified by random vector [ 0.37307137  0.75216642 -1.52440778]
Range space is defined by [array([-0.01209688, -0.44405777,  0.89591649]), array([ 0.99988947, -0.01311701,  0.00699935])]
Verified by random vector y: [ 0.02043883 -0.5958463   0.04576914]
Solving the linear system for x yielded: [[ 8.31057149e+13 -1.08023260e+17  7.74040320e+16]
 [ 2.39867516e+12 -0.00000000e+00 -7.68619005e+15]
 [-1.68899434e+08  7.54908396e+13 -2.39652227e+14]]
Only null space is from the zero vector
The matrix is not invertible
Null space is defined by [array([0.54705244, 0.83709834])]
Verified by random vector [-0.2323071  -0.35547576]
The matrix is not invertible


In [9]:
search_spaces(mtx1)


KeyboardInterrupt



In [5]:
rand_vector

NameError: name 'rand_vector' is not defined

In [82]:
np.shape(V)

(2, 2)

In [101]:
    U, s, V = np.linalg.svd(mtx1, full_matrices = True)
    index_null = np.where(s==0)

In [102]:
index_null

(array([], dtype=int64),)

Matrix 2

In [ ]:
mtx2= mtxN['mtx2']
print(mtx2)

In [ ]:
u,s,v = la.svd(mtx2, full_matrices=True, compute_uv=True, hermitian=False)

Matrix 3

In [ ]:
mtx3= mtxN['mtx3']
print(mtx3)

In [ ]:
u,s,v = la.svd(mtx3, full_matrices=True, compute_uv=True, hermitian=False)

Matrix 4

In [ ]:
mtx4= mtxN['mtx4']
print(mtx4)

In [ ]:
u,s,v = la.svd(mtx4, full_matrices=True, compute_uv=True, hermitian=False)